import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import AuthContext from "./context/AuthContext";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Remember",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body className="relative flex flex-col items-center">
        <AuthContext>
          <Header />
          <main className="w-full px-6 mx-auto mt-16 grow max-w-7xl">
            {children}
          </main>
        </AuthContext>
      </body>
    </html>
  );
}
